import assert from 'node:assert/strict';
import { createPost, postPriceLabel, validatePost, type PostInput } from '../src/data/publishedPosts.ts';
const author = { nickname: 'duck', neighborhood: '서초동', secondaryNeighborhood: '역삼동', tradePlace: '서초동', pickupAddress: '서울시 강남구' };
const input: PostInput = { title: ' 게임 주변기기 ', description: ' 설명 ', category: '디지털기기', photos: [], items: [{ id: 'one', name: '거치대', price: '5000', quantity: 3 }, { id: 'two', name: '케이스', price: '8000', quantity: null }], giveaway: false, directBuy: true, offers: true, giveawayRequests: false, secondary: true };
assert.equal(validatePost(input), null);
const post = createPost(input, author);
assert.equal(post.title, '게임 주변기기');
assert.equal(post.items[0].quantity, 3);
assert.equal(post.items[1].quantity, 1);
assert.equal(postPriceLabel(post), '5,000~8,000원');
assert.ok(validatePost({ ...input, title: ' ' }));
assert.ok(validatePost({ ...input, category: null }));
assert.ok(validatePost({ ...input, description: '' }));
assert.ok(validatePost({ ...input, items: [] }));
for (const price of ['', '0', '-1', '1.5', 'NaN', '9007199254740992']) assert.ok(validatePost({ ...input, items: [{ ...input.items![0], price }] }));
assert.ok(validatePost({ ...input, items: [{ ...input.items![0], quantity: 0 }] }));
const free = createPost({ ...input, giveaway: true, giveawayRequests: true, items: [{ ...input.items![0], price: '' }] }, author);
assert.equal(free.items[0].price, 0);
assert.equal(free.directBuy, false);
assert.equal(free.offers, false);
assert.equal(postPriceLabel(free), '나눔');
input.items![0].name = '이후 변경';
assert.equal(post.items[0].name, '거치대');
console.log('PASS: publishing validation, price ranges, quantity snapshot, free-post normalization.');
